package consts

const (
	PLUS_PRIVILEGE_DISCOUNT uint = 1001
	// PLUS_PRIVILEGE_POINTS_MULTIPLE PLUS 购物赠送积分倍数（PLUS_PRIVILEGE_POINTS_MULTIPLE）
	PLUS_PRIVILEGE_POINTS_MULTIPLE uint = 1002
	// PLUS_PRIVILEGE_FREE_SHIPPING PLUS 免运费（PLUS_PRIVILEGE_FREE_SHIPPING）
	PLUS_PRIVILEGE_FREE_SHIPPING uint = 1003
	// PLUS_PRIVILEGE_VOUCHER PLUS 权益券（PLUS_PRIVILEGE_VOUCHER）
	PLUS_PRIVILEGE_VOUCHER uint = 1004
)
